version: '3.1'

services:
  jupyterlab:
    container_name: jupyterlab
    build:
      context: .
    env_file:
      - ./notebook.env
    ports:
        - 8888:8888
    volumes:
        - ./projects:/notebook
